---
- hosts: web
  become: yes
  become_method: sudo
  tasks:

  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  
    
  - name: start nginx
    service:
      name: nginx
      state: started
    when: ansible_facts['os_family'] == "Debian"